MUTATION_RATE = .5
CROSSOVER_RATE = 1
FIGSIZE=(12, 6)
OUTPUT = 'output'
ANALYSIS ='analysis'
EXPERIMENTS ='experiments'
EXPERIMENT ='experiment'
FITNESS = 'fitness'
NSGA_II = 'nsga_ii'
BILEVEL_UPPER = 'bilevel_upper'
BILEVEL_LOWER = 'bilevel_lower'
